---
entrypoint: "gunicorn -b :$PORT main:app"
env: flex
handlers:
  -
    script: main.app
    url: .*
runtime: python
runtime_config:
  python_version: 3
threadsafe: true

manual_scaling:
    instances: 1

resources:
    cpu: 4
    memory_gb: 8
    disk_size_gb: 10